# Global config
global:
  scrape_interval: 15s # How often Prometheus will scrape metrics
  evaluation_interval: 15s # How often Prometheus will evaluate rules

# Scrape configurations
scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      # - targets: ['localhost:9090'] # might need to change back to localhost
      - targets: ['queryhawk-prometheus:9090']

  # Monitor our Express backend to collect metrics about queries
  - job_name: 'express'
    static_configs:
      # - targets: ['localhost:4002']
      - targets: ['backend:4002']

  # Add this to your prometheus.yml
  # - job_name: 'test_config'
  #   static_configs:
  #     - targets: ['test-target:1234']

  # Dynamic PostgreSQL monitoring
  - job_name: 'postgres-exporters'
    file_sd_configs:
      - files:
          # - '/etc/prometheus/postgres_targets/*.yml'
          - '/var/prometheus/postgres_targets/*.yml'
        refresh_interval: 5s
    relabel_configs:
      # Add user_id as a label
      - source_labels: ['__meta_file_content_labels_user_id']
        target_label: user_id
      # Keep the original instance label
      - source_labels: ['__meta_file_content_labels_instance']
        target_label: instance
      - source_labels: []
        target_label: '__metrics_path__'
        replacement: '/metrics'

  # OpenTelemetry collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
# List of metrics that will be collected:
#
# PostgreSQL Metrics (per database):
# - pg_stat_database_tup_fetched     # Rows fetched
# - pg_stat_database_tup_inserted    # Rows inserted
# - pg_stat_database_tup_updated     # Rows updated
# - pg_stat_database_tup_deleted     # Rows deleted
# - pg_stat_database_conflicts       # Query conflicts
# - pg_stat_activity_count          # Active connections
# - pg_stat_bgwriter_buffers        # Buffer usage
#
# Express Backend Metrics:
# - http_request_duration_seconds    # How long requests take
# - http_requests_total             # Number of requests
# - query_execution_time_seconds    # How long SQL queries take
# - query_errors_total             # Number of failed queries
# - active_connections             # Current number of connections
# - memory_usage_bytes             # Server memory use
#
# Prometheus Self-Monitoring:
# - prometheus_targets              # How many targets are being monitored
# - prometheus_notifications_sent   # Alert notifications
# - prometheus_scrape_duration     # How long scrapes take
# - prometheus_storage_samples     # How many data points stored
