apiVersion: 1

datasources:
  - name: Alloy
    type: prometheus
    access: proxy
    url: http://grafana-alloy:12345
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      prometheusUrl: http://grafana-alloy:12345
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
    secureJsonData: {}
    version: 1
