apiVersion: 1

datasources:
  - name: Alloy
    type: prometheus
    access: proxy
    url: http://mimir:9009
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      prometheusUrl: http://mimir:9009
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
    secureJsonData: {}
    version: 1
